from pydantic import BaseModel, Field
from agno.agent import Agent
from agno.models.openai import OpenAIChat


class DatasetMetadata(BaseModel):
    """Metadata generated by analyzing the dataset"""
    collection_name: str = Field(..., description="Suggested collection name (snake_case, descriptive)")
    description: str = Field(..., description="Detailed description of what this dataset contains and its purpose")
    data_category: str = Field(..., description="Category (e.g., 'customer_feedback', 'transactions', 'communications', 'products')")
    
    # Field analysis
    field_descriptions: dict[str, str] = Field(..., description="Map of field_name to human-readable description")
    key_fields: list[str] = Field(..., description="Most important fields for analysis")
    
    # Semantic search configuration
    embedding_fields: list[str] = Field(default_factory=list, description="Text fields optimal for embedding/vector search (rich text content)")
    primary_text_field: str | None = Field(default=None, description="Main text field for semantic search (e.g., 'content', 'review_text', 'message')")
    combined_text_fields: list[str] | None = Field(default=None, description="Fields to concatenate for richer embeddings (e.g., ['title', 'content'])")
    
    # Data characteristics
    estimated_use_cases: list[str] = Field(..., description="Potential use cases for this data")
    data_quality_notes: str = Field(default="", description="Notes on data quality, missing values, etc.")
    
    # Suggested relationships
    potential_joins: list[str] = Field(default_factory=list, description="Fields that could join with other collections")


def create_data_ingestion_agent(model: OpenAIChat) -> Agent:
    """
    Agent that analyzes uploaded data files and generates comprehensive metadata.
    
    This agent:
    1. Examines the structure and content of the data
    2. Generates human-readable descriptions
    3. Identifies key fields and their purposes
    4. Suggests use cases and relationships
    """
    return Agent(
        name="DataIngestionAnalyzer",
        role="Data File Analysis and Metadata Generation",
        model=model,
        description="""Analyze uploaded data files to generate comprehensive metadata.
        
        You will receive:
        - Filename
        - Column names and data types
        - Sample rows (first 5-10 rows)
        - Basic statistics (row count, null counts, etc.)
        
        Your job is to understand what this data represents and generate useful metadata
        that will help users query and analyze it later.
        """,
        instructions=[
            "Analyze the column names and sample data to understand the dataset's purpose",
            "Generate a clear, concise description of what this data represents",
            "Suggest a meaningful collection name (snake_case, descriptive)",
            "Identify the category (customer_feedback, transactions, communications, products, etc.)",
            "Write descriptions for each field explaining what it contains",
            "Identify the most important/useful fields for analysis",
            
            # Semantic search configuration
            "IMPORTANT: Identify text fields suitable for embedding/vector search:",
            "  - Look for fields with rich text content (paragraphs, sentences)",
            "  - Examples: 'content', 'review_text', 'message', 'description', 'comment', 'feedback'",
            "  - Exclude short/categorical text like 'status', 'category', 'author'",
            "  - Set primary_text_field to the MAIN content field for semantic search",
            "  - Set combined_text_fields if multiple fields should be concatenated (e.g., title + body)",
            "  - List all good embedding candidates in embedding_fields",
            
            "Suggest potential use cases for this data",
            "Note any data quality issues (missing values, inconsistencies)",
            "Identify fields that could be used to join with other datasets (IDs, keys)",
            "Be specific and practical - think about how analysts will use this data"
        ],
        output_schema=DatasetMetadata,
        markdown=False,
        debug_mode=False,
    )


class DataPreview(BaseModel):
    """Preview of uploaded data for analysis"""
    filename: str
    row_count: int
    columns: dict[str, str]  # column_name -> inferred_type
    sample_rows: list[dict]  # First few rows
    null_counts: dict[str, int] | None = None
    unique_counts: dict[str, int] | None = None

